

#ifndef DIMINUIREMAXDIMIN_FUNZIONI_FUNZIONI_H
#define DIMINUIREMAXDIMIN_FUNZIONI_FUNZIONI_H

void diminuireMaxDiMin(int *pNum1, int *pNum2, int *pNum3);

#endif //DIMINUIREMAXDIMIN_FUNZIONI_FUNZIONI_H
